name: FitNesse Composite Test No FitSharp

on: [workflow_dispatch]

jobs:
  fitnesse-runner:
    runs-on: ubuntu-latest
    name: Run a FitNesse test or suite (without FitSharp)
    env:
      FIXTURES: ${{github.workspace}}/fixtures
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: FitNesse run
        uses: essenius/fitnesse-composite-action@v0.37
        with:
          test-spec: SimpleTest?test
          fixture-folder: ${{github.workspace}}/simpleDemo
          test-result-artifact: fitnesse-demosuite
          fitnesse-folder: ${{github.workspace}}/simpleDemo
