# GitHub Actions to execute FitNesse with FitSharp .NET

name: FitNesse/FitSharp Setup and Execute
on: push
jobs:
  FitNesse:
    runs-on: ubuntu-latest
    env: 
      SLN_PATH : ${{secrets.SLN_PATH}} 
      TARGET_FOLDER : ${{secrets.TARGET_FOLDER}}
      FITNESSE_DOWNLOAD_URL : ${{secrets.FITNESSE_URL}}
      FIXTURE_PATH : ${{secrets.FIXTURE_PATH}}
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore SLN_PATH
      
    - name: Build
      run: dotnet build SLN_PATH
    
    - name: Install wget
      run: sudo apt install wget
   
    - name: Install mono
      run: sudo apt install mono-complete
      
    - name: Download FitNesse and Fitsharp
      run: |
        pwd
        mkdir TARGET_FOLDER
        cd TARGET_FOLDER
        wget FITNESSE_DOWNLOAD_URL
        wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
        mono nuget.exe install FitSharp -ExcludeVersion
   
